workspace: workspace.yaml

dataset:
  name: IU_RSSD_locbox_-30_-20_-65_-55_depth_600_T_600_750
  input_dir: ${paths.downloads_root}/source_array_event_download/IU_RSSD_locbox_-30_-20_-65_-55_depth_600_T_600_750
  noise_dir: ${paths.downloads_root}/source_array_noise_download/IU_RSSD_locbox_-30_-20_-65_-55_depth_600_T_600_750
  output_dir: ${paths.real_data_root}/IU_RSSD_locbox_-30_-20_-65_-55_depth_600_T_600_750

processing:
  downsample_hz: 2
  bandpass: [0.02, 0.4]

qc:
  snr_component: UZ
  snr_threshold: 1.5
  plot_summary: true
