workspace: workspace.yaml

defaults:
  stfshape: "dGaussian"
  is3c: true
  comp: "Z"
  sigma: 0.02
  num_chains: 8
  totalSteps: 500000
  burnInSteps: 400000
  nSaveModels: 200
  actionsPerStep: 1
  maxN: 20
  man_stf: false
  ampRange: [-1.0, 1.0]
  slwRange: [2.0, 10.0]
  minSpace: 1.0
  CDopt: 3
  locDiff: false
  distDiffRange: [-5.0, 5.0]
  bazDiffRange: [-5.0, 5.0]
  fitAtts: true
  fitLoge: true
  fitPhase: true
  normOpt: 1
  isMars: false
  srcArray: false
  pref: 0.0
  ref_manual: false
  refLat: 0.0
  refLon: 0.0
  refBaz: 0.0

experiments:
  - dataset: "InSight_S1133c_VEL_0p200_0p600Hz_5Hz_20b_30a_P"
    isMars: true
    srcArray: true
    CDopt: 3
    runname: "test_run_8c"

  - dataset: "InSight_S0820a_VEL_0p200_0p500Hz_5Hz_20b_30a_P"
    isMars: true
    srcArray: true
    CDopt: 3
    runname: "test_run_8c"

  - dataset: "GlitchNet_S1222a_VEL_FROM_DISP_0p200_0p600Hz_5Hz"
    isMars: true
    srcArray: true
    CDopt: 3
    runname: "test_run_8c"

  - dataset: "InSight_S0235b_VEL_0p200_0p700Hz_5Hz_20b_30a_P"
    isMars: true
    srcArray: true
    CDopt: 3
    runname: "test_run_8c"
