workspace: workspace.yaml

dataset:
  name: 201111221848_P_45_48
  input_dir: ${paths.downloads_root}/event_download/201111221848_P_45_48
  noise_dir: ${paths.downloads_root}/noise_download/201111221848_P_45_48
  output_dir: ${paths.real_data_root}/201111221848_P_45_48_TAPIR

processing:
  bandpass: [0.02, 0.5]
  downsample_hz: 5
  time_window: [0, 100]

qc:
  snr_component: UZ
  snr_threshold: 0
  plot_summary: true
